# Generated by Django 4.2.21 on 2026-01-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='base_currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='NGN', max_length=3),
        ),
    ]
