# Generated by Django 4.2.21 on 2026-02-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_type"),
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
        ),
    ]
